CREATE TABLE `user_log` (
    `USER_LOG` INT NOT NULL AUTO_INCREMENT,
    `USER_ID` INT NOT NULL,
    `ACTION_TYPE` VARCHAR(30) NULL,
    `BEFORE_DATA` JSON NULL,
    `AFTER_DATA` JSON NULL,
    `CREATED_AT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`USER_LOG`),
    FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
);

CREATE TABLE `book_log` (
    `BOOK_LOG` INT NOT NULL AUTO_INCREMENT,
    `BOOK_ID` INT NOT NULL,
    `ACTION_TYPE` VARCHAR(30) NULL,
    `BEFORE_DATA` JSON NULL,
    `AFTER_DATA` JSON NULL,
    `CREATED_AT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`BOOK_LOG`),
    FOREIGN KEY (`BOOK_ID`) REFERENCES `books` (`BOOK_ID`)
);

DROP TABLE `manage_log`;