CREATE TABLE popular_keyword (
         ID INT AUTO_INCREMENT PRIMARY KEY,
         KEYWORD VARCHAR(100) NOT NULL,
         COUNT INT NOT NULL DEFAULT 0,
         CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
         UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);