CREATE TABLE `payment` (
    `PAYMENT_ID` INT NOT NULL AUTO_INCREMENT,
    `ORDER_ID` INT NOT NULL,
    `USER_ID` INT NOT NULL,

    -- PG사 구분 (전략 선택용)
    `PG_PROVIDER` VARCHAR(30) NOT NULL
    CHECK (`PG_PROVIDER` IN ('IAMPORT', 'TOSS_PAYMENTS')),

    -- 기본 결제 정보
    `PAYMENT_KEY` VARCHAR(200) NULL,
    `ORDER_UUID` VARCHAR(100) NOT NULL,
    `PAYMENT_AMOUNT` INT NOT NULL,
    `PAYMENT_METHOD` VARCHAR(30) NULL,

    -- 결제 상태
    `PAYMENT_STATUS` VARCHAR(30) NOT NULL DEFAULT 'PENDING'
    CHECK (`PAYMENT_STATUS` IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELED')),

    -- PG사별 응답 데이터
    `PG_RESPONSE_DATA` JSON NULL,

    -- 에러 정보
    `ERROR_CODE` VARCHAR(50) NULL,
    `ERROR_MESSAGE` VARCHAR(255) NULL,

    -- 타임스탬프
    `CREATED_AT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP(0) NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`PAYMENT_ID`),
    FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`) ON DELETE CASCADE
);