services:
  mysql:
    image: mysql:8.0
    container_name: bookshop-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: book_shop
      MYSQL_USER: jihoon
      MYSQL_PASSWORD: 1234
    command: >
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower-case-table-names=0
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bookshop-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bookshop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bookshop-network
    command: redis-server --appendonly yes

  flyway:
    image: flyway/flyway:9.22.3
    container_name: bookshop-flyway
    restart: "no"
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    networks:
      - bookshop-network
    depends_on:
      mysql:
        condition: service_healthy
    command: [
      "-url=jdbc:mysql://mysql:3306/book_shop?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul",
      "-user=jihoon",
      "-password=1234",
      "-locations=filesystem:/flyway/sql",
      "migrate"
    ]

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  bookshop-network:
    driver: bridge