services:
  mysql:
    build: .
    container_name: bookstore-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bookstore-network

volumes:
  mysql-data:
    driver: local

networks:
  bookstore-network:
    driver: bridge